export const PROFILE_EVENTS = {
  LOAD_INITIAL_DATA_START: 'LOAD_INITIAL_DATA_START',
  LOAD_INITIAL_DATA_SUCCESS: 'LOAD_INITIAL_DATA_SUCCESS',
  LOAD_INITIAL_DATA_FAILURE: 'LOAD_INITIAL_DATA_FAILURE',

  FETCH_META_DATA_START: 'FETCH_META_DATA_START',
  FETCH_META_DATA_SUCCESS: 'FETCH_META_DATA_SUCCESS',
  FETCH_META_DATA_FAILURE: 'FETCH_META_DATA_FAILURE',

  FETCH_PROFILE_START: 'FETCH_PROFILE_START',
  FETCH_PROFILE_SUCCESS: 'FETCH_PROFILE_SUCCESS',
  FETCH_PROFILE_FAILURE: 'FETCH_PROFILE_FAILURE',

  DELETE_ACCOUNT_START: 'SIGNUP_START',
  DELETE_ACCOUNT_SUCCESS: 'SIGNUP_SUCCESS',
  DELETE_ACCOUNT_FAILURE: 'SIGNUP_FAILURE',
}
