export const MISC_EVENTS = {
  FETCH_META_DATA_START: 'FETCH_META_DATA_START',
  FETCH_META_DATA_SUCCESS: 'FETCH_META_DATA_SUCCESS',
  FETCH_META_DATA_FAILURE: 'FETCH_META_DATA_FAILURE',

  FETCH_LIST_DATA_START: 'FETCH_LIST_DATA_START',
  FETCH_LIST_DATA_SUCCESS: 'FETCH_LIST_DATA_SUCCESS',
  FETCH_LIST_DATA_FAILURE: 'FETCH_LIST_DATA_FAILURE',
}
