export const DASHBOARD_EVENTS = {
  FETCH_META_DATA_START: 'FETCH_META_DATA_START',
  FETCH_META_DATA_SUCCESS: 'FETCH_META_DATA_SUCCESS',
  FETCH_META_DATA_FAILURE: 'FETCH_META_DATA_FAILURE',

  FETCH_DETAIL_META_DATA_START: 'FETCH_DETAIL_META_DATA_START',
  FETCH_DETAIL_META_DATA_SUCCESS: 'FETCH_DETAIL_META_DATA_SUCCESS',
  FETCH_DETAIL_META_DATA_FAILURE: 'FETCH_DETAIL_META_DATA_FAILURE',

  FETCH_LIST_DATA_START: 'FETCH_LIST_DATA_START',
  FETCH_LIST_DATA_SUCCESS: 'FETCH_LIST_DATA_SUCCESS',
  FETCH_LIST_DATA_FAILURE: 'FETCH_LIST_DATA_FAILURE',

  FETCH_LIST_DETAIL_DATA_START: 'FETCH_LIST_DETAIL_DATA_START',
  FETCH_LIST_DETAIL_DATA_SUCCESS: 'FETCH_LIST_DETAIL_DATA_SUCCESS',
  FETCH_LIST_DETAIL_DATA_FAILURE: 'FETCH_LIST_DETAIL_DATA_FAILURE',
}
