require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'

target 'modulebuilder' do

  pod 'FirebaseCore', :modular_headers => true
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  config = use_native_modules!
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"

  use_react_native!(:path => config["reactNativePath"])

  target 'modulebuilderTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'modulebuilder-tvOS' do
  # Pods for modulebuilder-tvOS

  target 'modulebuilder-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end