export const ORG_EVENTS = {
  FETCH_ORG_SETTINGS_START: 'FETCH_ORG_SETTINGS_START',
  FETCH_ORG_SETTINGS_SUCCESS: 'FETCH_ORG_SETTINGS_SUCCESS',
  FETCH_ORG_SETTINGS_FAILURE: 'FETCH_ORG_SETTINGS_FAILURE',

  FETCH_CONFIG_MASTER_START: 'FETCH_CONFIG_MASTER_START',
  FETCH_CONFIG_MASTER_SUCCESS: 'FETCH_CONFIG_MASTER_SUCCESS',
  FETCH_CONFIG_MASTER_FAILURE: 'FETCH_CONFIG_MASTER_FAILURE',
}
