export const AUTH_EVENTS = {
  INVALID_INPUT: 'INVALID_INPUT',
  SIGNUP_ACTION: 'SIGNUP_ACTION',
  LOGIN_ACTION: 'LOGIN_ACTION',
  RESET_PASSWORD: 'RESET_PASSWORD',
  VERIFICATION_ACTION: 'VERIFICATION_ACTION',
  RESEND_TOKEN: 'RESEND_TOKEN',
}
