export const AUTH_EVENTS = {
  INVALID_INPUT: 'INVALID_INPUT',

  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  RESET_PASSWORD: 'RESET_PASSWORD_START',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',
  RESET_PASSWORD_START: 'RESET_PASSWORD_START',
  VERIFICATION_START: 'VERIFICATION_START',
  VERIFICATION_SUCCESS: 'VERIFICATION_SUCCESS',
  VERIFICATION_FAILURE: 'VERIFICATION_FAILURE',

  RESEND_TOKEN_START: 'RESEND_TOKEN_START',
  RESEND_TOKEN_SUCCESS: 'RESEND_TOKEN_SUCCESS',
  RESEND_TOKEN_FAILURE: 'RESEND_TOKEN_FAILURE',
}
