export const FORM_EVENTS = {
  FETCH_META_DATA_START: 'FETCH_META_DATA_START',
  FETCH_META_DATA_SUCCESS: 'FETCH_META_DATA_SUCCESS',
  FETCH_META_DATA_FAILURE: 'FETCH_META_DATA_FAILURE',

  FETCH_ENTITY_CONFIG_START: 'FETCH_ENTITY_CONFIG_START',
  FETCH_ENTITY_CONFIG_SUCCESS: 'FETCH_ENTITY_CONFIG_SUCCESS',
  FETCH_ENTITY_CONFIG_FAILURE: 'FETCH_ENTITY_CONFIG_FAILURE',

  POST_META_DATA_START: 'POST_META_DATA_START',
  POST_META_DATA_SUCCESS: 'POST_META_DATA_SUCCESS',
  POST_META_DATA_FAILURE: 'POST_META_DATA_FAILURE',
  POST_META_DATA_INVALID_INPUT: 'POST_META_DATA_INVALID_INPUT',
}
